In [47]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

In [149]:
meas_cycle = [
"[0,1]", "[1,3]",
"[1,3]", "[3,4]",
"[3,4]", "[4,0]",
"[4,0]", "[0,1]"]

Ncycle = 1

states = ["00","01","10","11"]

In [150]:
features =  ["cycle"+str(c)+"-"+str(m)+"-"+ str(s) for c in range(Ncycle) for m in meas_cycle for s in states]

In [152]:
features = ["theta"] + features

In [185]:
data_dict = np.load("../Downloads/num_reps=8_num_times=20.npy", allow_pickle=True)

In [199]:
len(data_dict[0]["all_syndromes"])

20

In [186]:
def parseSyn(data):
    vals = []
    for k in data:
        [vals.append([i[0], i[1]]) for i in data[k]]
        #print(k,[[i[0], i[1]] for i in data[k]])
    dic = {}
    for v in vals:
        if v[0] not in dic.keys():
            dic[v[0]] = v[1]
        else:
            dic[v[0]] += v[1]
    Ns = np.zeros((8,4))
    
    for key in dic:
        for n,j in enumerate(key.split(" ")):
            Ns[n][states.index(j)] += dic[key]
    return Ns/1024

In [202]:
dset = []
for d in data_dict:
    for l in range(len(d["all_syndromes"])):
        dset.append([d["theta"]] + list(parseSyn(d["all_syndromes"][l]).flatten()))

In [203]:
df = pd.DataFrame(dset, columns= features)

In [204]:
df

theta  cycle0-[0,1]-00  cycle0-[0,1]-01  cycle0-[0,1]-10  \
0     0.000000         0.513672         0.005859         0.008789   
1     0.000000         0.485352         0.006836         0.006836   
2     0.000000         0.505859         0.005859         0.008789   
3     0.000000         0.521484         0.007812         0.011719   
4     0.000000         0.505859         0.005859         0.004883   
...        ...              ...              ...              ...   
3995  6.251769         0.492188         0.003906         0.001953   
3996  6.251769         0.497070         0.005859         0.001953   
3997  6.251769         0.498047         0.008789         0.004883   
3998  6.251769         0.502930         0.009766         0.005859   
3999  6.251769         0.503906         0.010742         0.006836   

      cycle0-[0,1]-11  cycle0-[1,3]-00  cycle0-[1,3]-01  cycle0-[1,3]-10  \
0            0.471680         0.507812         0.007812         0.008789   
1            0.500977         0.487305         0.003906         0.008789   
2            0.479492         0.505859         0.012695         0.004883   
3            0.458984         0.521484         0.013672         0.007812   
4            0.483398         0.492188         0.010742         0.009766   
...               ...              ...              ...              ...   
3995         0.501953         0.481445         0.008789         0.010742   
3996         0.495117         0.495117         0.005859         0.005859   
3997         0.488281         0.499023         0.006836         0.006836   
3998         0.481445         0.501953         0.006836         0.011719   
3999         0.478516         0.505859         0.004883         0.011719   

      cycle0-[1,3]-11  cycle0-[1,3]-00  ...  cycle0-[4,0]-10  cycle0-[4,0]-11  \
0            0.475586         0.509766  ...         0.010742         0.471680   
1            0.500000         0.480469  ...         0.011719         0.504883   
2            0.476562         0.507812  ...         0.009766         0.470703   
3            0.457031         0.521484  ...         0.011719         0.459961   
4            0.487305         0.491211  ...         0.017578         0.486328   
...               ...              ...  ...              ...              ...   
3995         0.499023         0.480469  ...         0.013672         0.500977   
3996         0.493164         0.487305  ...         0.012695         0.490234   
3997         0.487305         0.500000  ...         0.012695         0.492188   
3998         0.479492         0.504883  ...         0.018555         0.477539   
3999         0.477539         0.504883  ...         0.016602         0.473633   

      cycle0-[4,0]-00  cycle0-[4,0]-01  cycle0-[4,0]-10  cycle0-[4,0]-11  \
0            0.502930         0.013672         0.010742         0.472656   
1            0.474609         0.011719         0.015625         0.498047   
2            0.509766         0.011719         0.012695         0.465820   
3            0.514648         0.009766         0.022461         0.453125   
4            0.480469         0.018555         0.021484         0.479492   
...               ...              ...              ...              ...   
3995         0.472656         0.010742         0.013672         0.502930   
3996         0.482422         0.014648         0.016602         0.486328   
3997         0.486328         0.008789         0.008789         0.496094   
3998         0.490234         0.016602         0.011719         0.481445   
3999         0.502930         0.016602         0.004883         0.475586   

      cycle0-[0,1]-00  cycle0-[0,1]-01  cycle0-[0,1]-10  cycle0-[0,1]-11  
0            0.504883         0.010742         0.013672         0.470703  
1            0.466797         0.017578         0.012695         0.502930  
2            0.503906         0.012695         0.008789         0.474609  
3            0.509766         0.023438         0.012695         0.454102  
4     

In [205]:
df.to_csv("dataset.csv")

In [184]:
df

theta  cycle0-[0,1]-00  cycle0-[0,1]-01  cycle0-[0,1]-10  \
0    0.000000         0.495117         0.004883         0.005859   
1    0.031416         0.508789         0.007812         0.003906   
2    0.062832         0.473633         0.003906         0.007812   
3    0.094248         0.482422         0.005859         0.004883   
4    0.125664         0.454102         0.003906         0.003906   
..        ...              ...              ...              ...   
195  6.126106         0.508789         0.004883         0.003906   
196  6.157522         0.509766         0.004883         0.009766   
197  6.188938         0.487305         0.003906         0.005859   
198  6.220353         0.465820         0.004883         0.005859   
199  6.251769         0.489258         0.005859         0.008789   

     cycle0-[0,1]-11  cycle0-[1,3]-00  cycle0-[1,3]-01  cycle0-[1,3]-10  \
0           0.494141         0.494141         0.008789         0.006836   
1           0.479492         0.507812         0.003906         0.006836   
2           0.514648         0.472656         0.006836         0.009766   
3           0.506836         0.478516         0.006836         0.006836   
4           0.538086         0.452148         0.010742         0.006836   
..               ...              ...              ...              ...   
195         0.482422         0.505859         0.008789         0.005859   
196         0.475586         0.505859         0.013672         0.005859   
197         0.502930         0.478516         0.013672         0.009766   
198         0.523438         0.461914         0.006836         0.004883   
199         0.496094         0.490234         0.011719         0.003906   

     cycle0-[1,3]-11  cycle0-[1,3]-00  ...  cycle0-[4,0]-10  cycle0-[4,0]-11  \
0           0.490234         0.500000  ...         0.009766         0.485352   
1           0.481445         0.504883  ...         0.009766         0.472656   
2           0.510742         0.470703  ...         0.015625         0.513672   
3           0.507812         0.477539  ...         0.014648         0.500000   
4           0.530273         0.449219  ...         0.009766         0.528320   
..               ...              ...  ...              ...              ...   
195         0.479492         0.502930  ...         0.009766         0.474609   
196         0.474609         0.514648  ...         0.009766         0.466797   
197         0.498047         0.481445  ...         0.017578         0.496094   
198         0.526367         0.460938  ...         0.004883         0.530273   
199         0.494141         0.491211  ...         0.007812         0.490234   

     cycle0-[4,0]-00  cycle0-[4,0]-01  cycle0-[4,0]-10  cycle0-[4,0]-11  \
0           0.494141         0.013672         0.006836         0.485352   
1           0.509766         0.013672         0.005859         0.470703   
2           0.460938         0.013672         0.009766         0.515625   
3           0.473633         0.012695         0.008789         0.504883   
4           0.453125         0.014648         0.012695         0.519531   
..               ...              ...              ...              ...   
195         0.506836         0.011719         0.013672         0.467773   
196         0.513672         0.011719         0.015625         0.458984   
197         0.473633         0.015625         0.019531         0.491211   
198         0.455078         0.011719         0.015625         0.517578   
199         0.492188         0.014648         0.010742         0.482422   

     cycle0-[0,1]-00  cycle0-[0,1]-01  cycle0-[0,1]-10  cycle0-[0,1]-11  
0           0.490234         0.006836         0.011719         0.491211  
1           0.510742         0.007812         0.013672         0.467773  
2           0.460938         0.008789         0.010742         0.519531  
3           0.475586         0.011719         0.014648         0.498047  
4           0.453125         0.013672         0.009766    

In [5]:
a = np.load("../Downloads/features.npy")
y = np.load("../Downloads/labels.npy")

In [10]:
for i in range(len(a)):
    print(a[i][0],"\n",y[i])

00 00 00 00 00 00 00 00 00 00 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10 01 00 00 00 00 00 00 11 10 
 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
11 11 11 00 01 10 11 00 01 10 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
11 11 11 11 11 11 11 11 11 11 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
11 11 11 11 11 11 11 11 11 11 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
11 10 01 00 11 10 01 00 11 10 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
00 00 00 0

In [39]:
labels = []
for ips in y:
    lab = []
    for line in ips:
        val = 0
        for n,bit in enumerate(line):
            val+= bit*2**n
        lab.append(val)
    labels.append(lab)

In [40]:
stati = ["00", "01", "10","11"]
X = []
for line in a:
    dato = []
    for me in line[0].split(" ")[::-1]:
        dato.append(stati.index(str(me)))
    X.append(dato)

In [41]:
df = pd.DataFrame(X, columns=[str(i) for i in range(10)])

In [48]:
df["label"] = labels

df.to_csv('artificial_dataset.csv')

In [49]:
df

0  1  2  3  4  5  6  7  8  9                   label
0   0  0  0  0  0  0  0  0  0  0    [0.0, 0.0, 0.0, 0.0]
1   2  3  0  0  0  0  0  0  1  2  [256.0, 9.0, 0.0, 0.0]
2   2  1  0  3  2  1  0  3  3  3    [0.0, 4.0, 0.0, 0.0]
3   3  3  3  3  3  3  3  3  3  3    [0.0, 0.0, 0.0, 0.0]
4   3  3  3  3  3  3  3  3  3  3    [0.0, 0.0, 0.0, 0.0]
.. .. .. .. .. .. .. .. .. .. ..                     ...
95  2  1  0  3  2  1  0  3  2  1    [0.0, 1.0, 0.0, 0.0]
96  2  2  2  2  2  3  3  3  3  3  [0.0, 32.0, 0.0, 16.0]
97  2  3  0  0  0  0  0  0  0  0  [256.0, 0.0, 0.0, 0.0]
98  3  0  1  2  3  0  1  3  3  3    [0.0, 0.0, 0.0, 8.0]
99  3  3  3  3  3  3  3  3  3  3    [0.0, 0.0, 0.0, 0.0]

[100 rows x 11 columns]

In [44]:
rf = RandomForestRegressor()
rf.fit(X,labels)

RandomForestRegressor()

In [45]:
rf.score(X,labels)

0.8713995686250543

In [46]:
from sklearn.metrics import r2_score

r2_score(labels, rf.predict(X))

0.8713995686250543

In [26]:
pred = rf.predict(X)

In [30]:
for i in range(len(pred)):
    print(pred[i] - labels[i])

[0. 0. 0. 0.]
[-27.76  20.84   0.     0.16]
[2.88 8.01 0.06 2.25]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[3.685e+01 1.000e+00 2.000e-02 8.000e-01]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[1.6  3.01 0.72 4.34]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[  0.64   6.42 -10.72   0.42]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 4.36  0.4   0.32 19.86]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[20.98  0.17  0.   21.26]
[ 12.88 -34.24   0.32   0.  ]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[15.68  0.17  0.4   4.92]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[8.33 0.08 0.4  6.76]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[40.88  8.91  0.32  0.16]
[0. 0. 0. 0.]
[0. 0. 0. 0.

In [32]:
np.sum((pred-labels)**2)/(4*len(labels))

253.19165099999998

In [37]:
(pred-labels)

array([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [-2.7760e+01,  2.0840e+01,  0.0000e+00,  1.6000e-01],
       [ 2.8800e+00,  8.0100e+00,  6.0000e-02,  2.2500e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 3.6850e+01,  1.0000e+00,  2.0000e-02,  8.0000e-01],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 1.6000e+00,  3.0100e+00,  7.2000e-01,  4.3400e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.

In [50]:
pred

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [2.2824e+02, 2.9840e+01, 0.0000e+00, 1.6000e-01],
       [2.8800e+00, 1.2010e+01, 6.0000e-02, 2.2500e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [3.7850e+01, 1.0000e+00, 2.0000e-02, 8.0000e-01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [1.6000e+00, 3.0100e+00, 8.7200e+00, 4.3400e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00,